### PR TITLE
Added Loyn dataset

### PR DESCRIPTION
**Pull request by gustavdelius**

### CODE REVIEW

**Comment by romunov** [comment]
Thank you for your contribution! I do have an ask, though. Could you modify column names of the data to make it more uniform. That is, all lowercase and replace dots with underscores?

`Site ABUND AREA DIST LDIST YR.ISOL GRAZE ALT` would then become `site abund area dist ldist yr_isol graze alt`.

**Comment by gustavdelius** [comment]
Given that this dataset is supposed to be used with the book by Zuur et.al., would it not be best to keep the variable names as they are, so that the code from the book will work unaltered?

**Comment by romunov** [comment]
That's a fair point.

**Comment by romunov** [comment]
When running the check, there is a mismatch in docs.

```
Data codoc mismatches from documentation object 'Loyn':
Variables in data frame 'Loyn'
Code: ABUND ALT AREA DIST GRAZE LDIST Site YR.ISOL
Docs: ABUND ALT AREA DIST GRAZE LDIST Site YEAR.ISOL
```
Can you fix that?

**Comment by gustavdelius** [comment]
Thank you for catching that. This happened because Table A.1 in the book has that mistake in it and I just copied that. I have now fixed the documentation.

**Pull request merged**
